
import Daye from "../src/images/daye.png"
import tfa from "../src/images/tfa.png"
import PowWow from "../src/images/powwownow.png"
import GoogleAds from "../src/images/googleads.png"
import DayeVitals from "../src/images/vitals.png"
import PoemPortraits from "../src/images/poemportraits.png"
import MoulinRouge from "../src/images/moulinrouge.png"
import RadicalLux from "../src/images/radicallux.png"
import RotaHome from "../src/images/rota.png"
import RollingStones from "../src/images/rollingstones.png"
import Audemars from "../src/images/audemars.png"
import Zown from "../src/images/zown.png"
import Scouty from "../src/images/scouty.png"
import SevenBridges from "../src/images/sevenbridges.png"

export const workObj =  [
    {builtWith: "NextJS, Node, Express",id: "scouty", title: "Scouty", description: "Whilst working with Scouty I have built their list feature including the ability to share lists add comments", image:Scouty,  href:"https://scouty.com/"  },
    {builtWith: "",id: "zown", title: "Zown", description: "I built freelanced for Zown and built their mobile application using expo/react native and their website using contentful.", image:Zown,  href:"https://zown.co/"  },
    {builtWith: "",id: "daye-ecommerce", title: "Daye Ecom platform", description: "Whilst at Daye I worked on the frontend feature development of the Daye Ecommerce site. This included a redesign using figma for the designs.", image:Daye,  href:"https://yourdaye.com/vitals/"  },
    {builtWith: "",id: '7bridges', title: "Seven Bridges", description: "Whilst working for seven bridges, I have refactored a large chunk of the application from a javascript class react application to a TypeScript React functional application, adding cypress for end to end testing and refactoring enzyme tests to the preferred jest and react testing library", image:SevenBridges, href: "https://www.the7bridges.com/" },
    {builtWith: "This site was built with React, Gatsby, Typescript and Prismic.",id: "daye-blog",title: "Daye blog", description: "I created Daye's Blog site from the ground up. The purpose of this site was to be faster and have an improved SEO compared to the old PHP blog site. I used Gatsby because as a static site generator it generates the content during build time which gives the site a much faster feel when clicking through the content. SEO is also improved as it's much easier for crawlers to find the content as it's built during build time rather than fetched afterwards.", image:DayeVitals, href:"https://yourdaye.com/vitals/" },
    {builtWith: "",id: 'rota', title: "Rota", description: "Whilst working at Rota, I have refactored a large chunk of the application from a javascript class react application to a TypeScript React functional application, adding cypress for end to end testing and refactoring enzyme tests to the preferred jest and react testing library", image:RotaHome, href: "https://www.rota.com/" },
    {builtWith: "This was built using Angular 2+ and the Spotify's API.",id: "moulin-rouge",title: "Moulin Rouge", description: "Whilst working at Phantom agency I worked on one of our clients Sony brief to promote their Moulin Rouge production launching in New York. The idea was a site that matched users spotify account with a Moulin Rouge character by grabbing their spotify playlist numbers.", image:MoulinRouge,  href:"https://wearebohemians.moulinrougemusicalalbum.com/#/home/" },
    {builtWith: "This was built using NextJs, Material UI library and formkit library to make the components as clean and as reusable as possible",id: "testing-for-all",title: "Testing For All", description: "I volunteered for Testing For All a not for profit covid-19 testing company. I was the main frontend engineer on this site working on the evenings and weekends alongside my full-time job.", image:tfa,  href:"//testingforall.app/"  },
    {builtWith: "This site was built with: Angular on the frontend, and python on the backend, maintaining any feature requests, bug fixes and design discussions.",id: "google-ads",title: "Google Ads", description: "Whilst working for the agency Phantom, one of the clients I worked on was Google. I maintained their Google Ads site. This was the main driver for Google and included feature development, bug fixing and general updates to their individual locales.", image:GoogleAds,  href:"https://ads.google.com/intl/en_gb/getstarted/"  },
    {builtWith: "This was built using ReactJs, Redux and python on the backend.",id: "powwownow",title: "PowWowNow", description: "During my time working for Powwownow I created the sign in journey. This included creating the Sign in, Sign out and Forgot password pages, I also created the FAQ page.", image:PowWow,  },
    {builtWith: "This site was built with Vanilla Javascript, no framework was used. I used the library Jump.js for the scrolling transitions.",id: "piguet-audemars",title: "Financial Times - Piguet Audemars", description: "Whilst at Phantom Agency, I worked on our Financial Times brief to create a prestigious, smooth site for the Audemars Piguet watch partnership. Unfortunately, this campaign has come to an end so the link is no longer available. But I can promise you it was very smooth :). The site had an about page, a video page which displayed the four watches in the campaign, and a carousel which displayed details about each watch.    ", image:Audemars,  },
    {builtWith: "This was built with Adobe Experience Manager (AEM), working with Photoshop and using javascript inputs for customisations.",id: "selfridges-rolling-stones",title: "Selfridges Rolling Stones", description: "During my time contracting for Selfridges, I created the Rolling Stones campaign site for the Selfridges homepage, I worked on the seasonal homepage site changes. I also worked on various feature developments across the site including adding a cookies bar.", image:RollingStones,  href:"//www.selfridges.com/GB/en/features/articles/selfridges-loves/the-rolling-stones-at-selfridges/"  },
    {builtWith: "",id: "poem-portraits",title: "Google Arts & Culture - Poem Portraits", description: "As a technical liaison I provided technical support to the non-technical product managers to help them better work with and mange the technical agencies building their marketing campaign sites. I managed this Poem Portraits site from a technical perspective", image:PoemPortraits,  href:"https://artsexperiments.withgoogle.com/poemportraits"  },
    {builtWith: "",id: "selfridges-radical-luxury",title: "Selfridges Radical Luxury", description: "I created the Radical Luxury campaign site for the Selfridges homepage, during my time contracting for Selfridges, I worked on the seasonal homepage site changes. I also worked on various feature developments across the site including adding a cookies bar.", image:RadicalLux,  href:"https://www.selfridges.com/GB/en/features/articles/selfridges-loves/the-rolling-stones-at-selfridges/"  },

]
